spring:
  datasource:

    url: jdbc:mysql://localhost:3306/pandemic?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Password1
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
    continue-on-error: true
  jpa:
    #For MySQL 8
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      #open-in-view: false
    properties:
      hibernate:
        format_sql: true
#  logging:
#    level:
#      org.springframework.security: DEBUG
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE